<?php

declare(strict_types=1);

namespace voku\tests;

/**
 * @internal
 */
final class PhpDocHelperTest extends \PHPUnit\Framework\TestCase
{
    public function testApi(): void
    {
        $result = (new \voku\PhpReadmeHelper\GenerateApi())->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base.md',
            [
                Dummy::class,
                DummyInterface::class,
            ]
        );

        static::assertSame(
            '[//]: # (AUTO-GENERATED BY "PHP README Helper": base file -> tests/fixtures/base.md)

# 😋 FOO BAR

## Description

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt ut labore et dolore 
magna aliquyam erat, sed diam voluptua. At vero eos et accusam 
et justo duo dolores et ea rebum. Stet clita kasd gubergren, 
no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem 
ipsum dolor sit amet, consetetur sadipscing elitr, sed diam 
nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam 
erat, sed diam voluptua. At vero eos et accusam et justo duo 
dolores et ea rebum. Stet clita kasd gubergren, no sea takimata 
sanctus est Lorem ipsum dolor sit amet.

# FOO BAR | API

Lorem ipsum dolor sit amet, consetetur ...

## Class methods

<p id="voku-php-readme-class-methods"></p><table><tr><td><a href="#withcallbackcallablestring-string-callback-string">withCallback</a>
</td><td><a href="#static-withemptyparamtypephpdocbool-parsedparamtag-array">withEmptyParamTypePhpDoc</a>
</td><td><a href="#withphpdocparamintnull-userandint">withPhpDocParam</a>
</td><td><a href="#withpsalmphpdoconlyparamlistint-userandint">withPsalmPhpDocOnlyParam</a>
</td></tr><tr><td><a href="#withreturntype-arrayint-int">withReturnType</a>
</td><td><a href="#withoutphpdocparambool-userandint-intstringnull">withoutPhpDocParam</a>
</td><td><a href="#withoutreturntype-falseint">withoutReturnType</a>
</td></tr></table>

## withCallback(callable(string): string $callback): string
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `callable(string): string $callback`

**Return:**
- `string`

--------

## static withEmptyParamTypePhpDoc(bool $parsedParamTag): array
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `bool $parsedParamTag <p>some more info ...</p>`

**Return:**
- `array`

--------

## withPhpDocParam(int[]|null $useRandInt): 
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `int[]|null $useRandInt`

**Return:**
- `TODO: __not_detected__`

--------

## withPsalmPhpDocOnlyParam(?list<int> $useRandInt): 
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `?list<int> $useRandInt`

**Return:**
- `TODO: __not_detected__`

--------

## withReturnType(): array<int, int>
<a href="#voku-php-readme-class-methods">↑</a>
this is a test

EXAMPLE: <code>
Dummy->withReturnType(); // [1, 2, 3]
<code>

**Parameters:**
__nothing__

**Return:**
- `array<int, int>`

--------

## withoutPhpDocParam(bool $useRandInt): int[]|string[]|null
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `bool $useRandInt`

**Return:**
- `int[]|string[]|null <p>foo</p>`

--------

## withoutReturnType(): false|int
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
__nothing__

**Return:**
- `false|int`

--------


## Interface methods

<p id="voku-php-readme-class-methods"></p><table><tr><td><a href="#barbool-foo-nullstring-foo2-bool">bar</a>
</td><td><a href="#foo-bool">foo</a>
</td></tr></table>

## bar(bool $foo, null|string $foo2): bool
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `bool $foo`
- `null|string $foo2`

**Return:**
- `bool`

--------

## foo(): bool
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
__nothing__

**Return:**
- `bool`

--------
',
            $result
        );
    }

    public function testApiWithProperties(): void
    {
        $result = (new \voku\PhpReadmeHelper\GenerateApi())->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_with_properties.md',
            [
                Dummy::class,
            ]
        );

        static::assertSame(
            '[//]: # (AUTO-GENERATED BY "PHP README Helper": base file -> tests/fixtures/base_with_properties.md)

## Properties

<p id="voku-php-readme-class-properties"></p><table><tr><td><a href="#public-string-bar">bar</a>
</td><td><a href="#public-int-foo">foo</a>
</td><td><a href="#public-nullarrayint-int-lall1">lall1</a>
</td><td><a href="#public-float-lall2">lall2</a>
</td></tr><tr><td><a href="#public-nullfloat-lall3">lall3</a>
</td></tr></table>

## public string $bar
<a href="#voku-php-readme-class-properties">↑</a>


--------

## public int $foo
<a href="#voku-php-readme-class-properties">↑</a>


--------

## public null|array<int, int> $lall1
<a href="#voku-php-readme-class-properties">↑</a>


--------

## public float $lall2
<a href="#voku-php-readme-class-properties">↑</a>


--------

## public null|float $lall3
<a href="#voku-php-readme-class-properties">↑</a>


--------


## Methods

<p id="voku-php-readme-class-methods"></p><table><tr><td><a href="#withcallbackcallablestring-string-callback-string">withCallback</a>
</td><td><a href="#static-withemptyparamtypephpdocbool-parsedparamtag-array">withEmptyParamTypePhpDoc</a>
</td><td><a href="#withphpdocparamintnull-userandint">withPhpDocParam</a>
</td><td><a href="#withpsalmphpdoconlyparamlistint-userandint">withPsalmPhpDocOnlyParam</a>
</td></tr><tr><td><a href="#withreturntype-arrayint-int">withReturnType</a>
</td><td><a href="#withoutphpdocparambool-userandint-intstringnull">withoutPhpDocParam</a>
</td><td><a href="#withoutreturntype-falseint">withoutReturnType</a>
</td></tr></table>

## withCallback(callable(string): string $callback): string
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `callable(string): string $callback`

**Return:**
- `string`

--------

## static withEmptyParamTypePhpDoc(bool $parsedParamTag): array
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `bool $parsedParamTag <p>some more info ...</p>`

**Return:**
- `array`

--------

## withPhpDocParam(int[]|null $useRandInt): 
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `int[]|null $useRandInt`

**Return:**
- `TODO: __not_detected__`

--------

## withPsalmPhpDocOnlyParam(?list<int> $useRandInt): 
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `?list<int> $useRandInt`

**Return:**
- `TODO: __not_detected__`

--------

## withReturnType(): array<int, int>
<a href="#voku-php-readme-class-methods">↑</a>
this is a test

EXAMPLE: <code>
Dummy->withReturnType(); // [1, 2, 3]
<code>

**Parameters:**
__nothing__

**Return:**
- `array<int, int>`

--------

## withoutPhpDocParam(bool $useRandInt): int[]|string[]|null
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `bool $useRandInt`

**Return:**
- `int[]|string[]|null <p>foo</p>`

--------

## withoutReturnType(): false|int
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
__nothing__

**Return:**
- `false|int`

--------

',
            $result
        );
    }

    public function testApiWithEnum(): void
    {
        $result = (new \voku\PhpReadmeHelper\GenerateApi())->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_with_enum.md',
            [
                DummyEnum::class,
            ]
        );

        static::assertSame(
            '[//]: # (AUTO-GENERATED BY "PHP README Helper": base file -> tests/fixtures/base_with_enum.md)

## Enum Cases

- `ACTIVE = \'active\'`
- `INACTIVE = \'inactive\'`
- `PENDING = \'pending\'`

## Enum Methods

<p id="voku-php-readme-class-methods"></p><table><tr><td><a href="#static-cases-array">cases</a>
</td><td><a href="#static-fromintstring-value-static">from</a>
</td><td><a href="#label-string">label</a>
</td><td><a href="#static-tryfromintstring-value-nullstatic">tryFrom</a>
</td></tr></table>

## static cases(): array
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
__nothing__

**Return:**
- `array`

--------

## static from(int|string $value): static
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `int|string $value`

**Return:**
- `static`

--------

## label(): string
<a href="#voku-php-readme-class-methods">↑</a>
Get the label for the enum case.

**Parameters:**
__nothing__

**Return:**
- `string`

--------

## static tryFrom(int|string $value): null|static
<a href="#voku-php-readme-class-methods">↑</a>


**Parameters:**
- `int|string $value`

**Return:**
- `null|static`

--------

',
            $result
        );
    }

    // -------------------------------------------------------------------------
    // Exception / guard tests
    // -------------------------------------------------------------------------

    public function testGenerateThrowsOnNonExistentFile(): void
    {
        // An empty file triggers the explicit 'Could not load file' exception path
        // (file_get_contents returns '' which is falsy, so the guard throws).
        $emptyFile = \sys_get_temp_dir() . '/readme_helper_empty.md';
        \file_put_contents($emptyFile, '');

        try {
            $this->expectException(\Exception::class);
            $this->expectExceptionMessageMatches('/Could not load file/');

            (new \voku\PhpReadmeHelper\GenerateApi())->generate(
                __DIR__ . '/',
                $emptyFile,
                [Dummy::class]
            );
        } finally {
            \unlink($emptyFile);
        }
    }

    public function testGenerateThrowsOnMissingFunctionListPlaceholder(): void
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessageMatches('/missing string.*__functions_list__/');

        // Use a fixture that has the index placeholder but not the list placeholder.
        (new \voku\PhpReadmeHelper\GenerateApi())->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_unit_enum.md',  // contains only enum_cases + functions_index + functions_list for DummyUnitEnum
            [Dummy::class]                             // but Dummy's placeholder is not in that template
        );
    }

    public function testGenerateThrowsOnMissingFunctionIndexPlaceholder(): void
    {
        // Write a temp template file with only the list placeholder, not the index.
        $tmpFile = \sys_get_temp_dir() . '/readme_helper_test_missing_index.md';
        \file_put_contents($tmpFile, '%__functions_list__voku\tests\Dummy__%');

        try {
            $this->expectException(\Exception::class);
            $this->expectExceptionMessageMatches('/missing string.*__functions_index__/');

            (new \voku\PhpReadmeHelper\GenerateApi())->generate(
                __DIR__ . '/',
                $tmpFile,
                [Dummy::class]
            );
        } finally {
            \unlink($tmpFile);
        }
    }

    // -------------------------------------------------------------------------
    // Configuration-flag tests
    // -------------------------------------------------------------------------

    public function testTodoModusDisabledOmitsPlaceholderForUnknownTypes(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();
        $api->todoModus = false;

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended.md',
            [DummyExtended::class]
        );

        // With todoModus=false a method that has no type info gets empty strings,
        // NOT the "TODO: __not_detected__" placeholder.
        static::assertStringNotContainsString('TODO: __not_detected__', $result);
        // The untyped param shows only the variable name.
        static::assertStringContainsString('$param', $result);
    }

    public function testSkipDeprecatedMethodsDefaultsToExcludingDeprecated(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();
        // Default: skipDeprecatedMethods = true → deprecatedMethod must NOT appear.
        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended.md',
            [DummyExtended::class]
        );

        static::assertStringNotContainsString('deprecatedMethod', $result);
    }

    public function testSkipDeprecatedMethodsDisabledIncludesDeprecated(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();
        $api->skipDeprecatedMethods = false;

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended.md',
            [DummyExtended::class]
        );

        // With the flag off the deprecated method MUST appear.
        static::assertStringContainsString('deprecatedMethod', $result);
    }

    public function testSkipLeadingUnderscoreDefaultsToExcludingUnderscoreMethods(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();
        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended.md',
            [DummyExtended::class]
        );

        static::assertStringNotContainsString('_internalHelper', $result);
    }

    public function testSkipLeadingUnderscoreDisabledIncludesUnderscoreMethods(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();
        $api->skipMethodsWithLeadingUnderscore = false;

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended.md',
            [DummyExtended::class]
        );

        static::assertStringContainsString('_internalHelper', $result);
    }

    public function testHideTheFunctionIndexSuppressesIndexTable(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();
        $api->hideTheFunctionIndex = true;

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended.md',
            [DummyExtended::class]
        );

        // The index table contains <table>…</table>; with the flag on it should be absent.
        static::assertStringNotContainsString('<table>', $result);
        // The method documentation itself must still be present.
        static::assertStringContainsString('normalMethod', $result);
    }

    public function testAutoDetectClassesWhenUseClassesIsNull(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();

        // Scan only DummyExtended.php so auto-detection finds exactly one class.
        $tmpFile = \sys_get_temp_dir() . '/readme_helper_autodetect.md';
        \file_put_contents(
            $tmpFile,
            '%__functions_list__voku\tests\DummyExtended__%' . "\n" .
            '%__functions_index__voku\tests\DummyExtended__%'
        );

        try {
            $result = $api->generate(__DIR__ . '/DummyExtended.php', $tmpFile, null);
            // Auto-detection must discover and output the normal method.
            static::assertStringContainsString('normalMethod', $result);
        } finally {
            \unlink($tmpFile);
        }
    }

    // -------------------------------------------------------------------------
    // Properties filter tests
    // -------------------------------------------------------------------------

    public function testPropertiesSkipLeadingUnderscoreByDefault(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended_with_properties.md',
            [DummyExtended::class]
        );

        // _underscoreProp must be hidden by default.
        static::assertStringNotContainsString('_underscoreProp', $result);
    }

    public function testPropertiesSkipLeadingUnderscoreDisabled(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();
        $api->skipPropertiesWithLeadingUnderscore = false;

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended_with_properties.md',
            [DummyExtended::class]
        );

        // With the flag off the underscore property must appear.
        static::assertStringContainsString('_underscoreProp', $result);
    }

    public function testPropertiesSkipPrivateByDefault(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended_with_properties.md',
            [DummyExtended::class]
        );

        // privateProp is private, so it must be hidden when access = ['public'].
        static::assertStringNotContainsString('privateProp', $result);
    }

    public function testReadonlyPropertySignatureIncludesReadonlyKeyword(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended_with_properties.md',
            [DummyExtended::class]
        );

        static::assertStringContainsString('readonly', $result);
        static::assertStringContainsString('readonlyProp', $result);
    }

    public function testStaticPropertySignatureIncludesStaticKeyword(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended_with_properties.md',
            [DummyExtended::class]
        );

        static::assertStringContainsString('static', $result);
        static::assertStringContainsString('staticProp', $result);
    }

    public function testNativeTypedPropertyUsesNativeTypeWhenNoPhpDoc(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended_with_properties.md',
            [DummyExtended::class]
        );

        // nativeTypedProp has type=string but no phpDocExtended → must show 'string'
        static::assertStringContainsString('string $nativeTypedProp', $result);
    }

    public function testPropertyTypeFromDefaultValueFallback(): void
    {
        $api = new \voku\PhpReadmeHelper\GenerateApi();

        $result = $api->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_extended_with_properties.md',
            [DummyExtended::class]
        );

        // defaultOnlyProp has no native type and no @var, so the type comes from
        // the default value ('hello' → string).
        static::assertStringContainsString('string $defaultOnlyProp', $result);
    }

    // -------------------------------------------------------------------------
    // Unit enum (cases without backing values)
    // -------------------------------------------------------------------------

    public function testApiWithUnitEnum(): void
    {
        $result = (new \voku\PhpReadmeHelper\GenerateApi())->generate(
            __DIR__ . '/',
            __DIR__ . '/fixtures/base_unit_enum.md',
            [DummyUnitEnum::class]
        );

        // Unit enum cases should appear WITHOUT a value.
        static::assertStringContainsString('- `FOO`', $result);
        static::assertStringContainsString('- `BAR`', $result);
        static::assertStringContainsString('- `BAZ`', $result);
        // And must NOT contain a '=' assignment.
        static::assertStringNotContainsString('FOO =', $result);
    }
}
